### ISSUE TITLE
No implementation found for void magick.ImageInfo.init() 

### ISSUE THREAD

**Issue by aaandreyev** [cherryleafroad/Android-ImageMagick7#4]
Hey, thanks for your work and contribution to open source community. 

For the past two days I've been trying to make this lib work, but still no progress. 
I'm trying to use it as a static .so lib through jmagick java interface. 
And at runtime I'm getting this error: 
`Suppressed: java.lang.UnsatisfiedLinkError: No implementation found for void magick.ImageInfo.init() (tried Java_magick_ImageInfo_init and Java_magick_ImageInfo_init__)
        at magick.ImageInfo.init(Native Method)
        at magick.ImageInfo.<init>(ImageInfo.java:35)`

Basically if we look inside **Magick.java** file, it says **System.loadLibrary("jmagick-7");**, so it
needs jmagick-7.so file inside libs folder. But there's nothing alike across the whole lib, I found
only one file called _Android-ImageMagick7/libjmagick-7/android/app/src/main/assets/usr/bin/arm64-v8a/magick_ , I've renamed it to jmagick-7.so, but it didn't work. 
Also I've rebuilt on my machine, but still got the same error above.

1. How to get rid of the UnsatisfiedLinkError error?
2. Why there's no jmagick-7.so file inside the lib, while Magick.java clearly requires it.
3. _Android-ImageMagick7/libjmagick-7/android/app/libs/arm64-v8a/libc++_shared.so_ what is this file, and should I load it dynamically in order to make the whole thing finally work?

Thanks

**Comment by cherryleafroad** [comment]
Your `UnsatisfiedLinkError` is happening because it requires a library, but none is being found. The file `magick` you used to rename into a `.so` library is only an `arm64-v8a` elf binary, not a library. You need to build the project from source to get a static library file. You can do this using a standard ndk build as referenced in [Android docs](https://developer.android.com/ndk/guides). The rest of the specific gradle support files to build it can be found in [libjmagick-7/android/app](/cherryleafroad/Android-ImageMagick7/tree/master/libjmagick-7/android/app).

1. Build the library as per instructions above. After you set up NDK as per Android requirements, you can run the `bat` file in the `jni` directory to make a build. Then place your library in the `app\libs\arch` folder (replace arch with appropriate arch, usually `arm64-v8a` and build your application). Android will add the library to the `apk/lib` folder, which will be recognized in the system path, and the java code will see the library.

2. You need to build the library. See above. The library should be named `libjmagick-7.so`

3. Some of the delegates use C++ coding instead of C. The C++ coding requires a special C++ support library. If you don't compile the C++ delegates, this library is not needed. No dynamic loading is needed, all the java and everything works out of the box once you set everything up. Also, if you build it yourself, just delete the prepackaged `libc++shared.so` file. Your build will generate one for you. Use that one. -> The reason it is there is because the [`magick` binary ](/cherryleafroad/Android-ImageMagick7/tree/master/libjmagick-7/android/app/src/main/assets/usr/bin/arm64-v8a) is linked against it.

The whole directory is pre-configured to use a binary, not a library. Given that everybody's needs are different, it didn't make sense for me to build the library and upload it anymore (the delegates are easily configurable in the mk files). If you absolutely must, there's a library in the [releases section](/cherryleafroad/Android-ImageMagick7/releases). I don't suggest using it though as it's an older version.

**Comment by cherryleafroad** [comment]
Anyways, I built it for you just to save time. But the instructions are above. You should follow them so you can stay up to date with any future code changes.

I build it using this configuration:

```
#----------------------------------------------------------------------------#
#                                  _           _     _                       #
#                  /\             | |         (_)   | |                      #
#                 /  \   _ __   __| |_ __ ___  _  __| |                      #
#                / /\ \ | '_ \ / _` | '__/ _ \| |/ _` |                      #
#               / ____ \| | | | (_| | | | (_) | | (_| |                      #
#              /_/    \_\_| |_|\__,_|_|  \___/|_|\__,_|                      #
#                                                                            #
#  _____                            __  __             _      _      ______  #
# |_   _|                          |  \/  |           (_)    | |    |____  | #
#   | |  _ __ ___   __ _  __ _  ___| \  / | __ _  __ _ _  ___| | __     / /  #
#   | | | '_ ` _ \ / _` |/ _` |/ _ \ |\/| |/ _` |/ _` | |/ __| |/ /    / /   #
#  _| |_| | | | | | (_| | (_| |  __/ |  | | (_| | (_| | | (__|   <    / /    #
# |_____|_| |_| |_|\__,_|\__, |\___|_|  |_|\__,_|\__, |_|\___|_|\_\  /_/     #
#                         __/ |                   __/ |                      #
#                        |___/                   |___/                       #
#                                                                            #
#----------------------------------------------------------------------------#

# list of supported architectures 
# https://developer.android.com/ndk/guides/application_mk.html

# mips32 have a bug with 64bit atomic counter, so if you need 
# this platform - plz, use gcc build
# DO NOT BUILD MORE THAN ONE AT THE SAME TIME, OR IT WILL FAIL
# BUILD THEM ONE AT A TIME
# armeabi-v7a is currently not supported
APP_ABI := arm64-v8a
APP_PLATFORM := android-24
NDK_TOOLCHAIN_VERSION := clang

# list of build-in STL's supported by NDK. 
# switch to clang STL in case of using this compiler
# https://developer.android.com/ndk/guides/cpp-support.html#runtimes

# Until NDK r16, the NDK's libc++ is only of beta quality. 
# Beginning with NDK r16, libc++ will be the preferred STL. 
# A future NDK release will remove the other options.
APP_STL := c++_shared

APP_CFLAGS   += -O3

APP_CPPFLAGS += -O3


#------------------------------------------
# Magick options

HDRI_ENABLE   := true
# 8, 16, 32
QUANTUM_DEPTH := 16


#------------------------------------------
# Whether to do a static or shared library
# build. Shared library builds are mandatory
# for jmagick builds.
#
# You can also choose to build a magick
# binary (NOT recommended to build a magick)
# binary when using jmagick. Because special
# paths must be set via code
#

STATIC_BUILD     := false
# magick bin requires magick wand API
BUILD_MAGICK_BIN := false
BUILD_MAGICKWAND := true


#------------------------------------------
# Types of builds available. OpenMP, OpenCL, or neither
# Neither will do a vanilla build without either feature

# openCL build requires special setup. Check the libopencl
# directory for more information
OPENCL_BUILD     := false
OPENMP_BUILD     := true


#------------------------------------------
# Enable or disable jmagick build
#
# - Enabling this will patch imagemagick for
# jmagick and android compatibility
#
# - Disabling this will compile the vanilla
# (unmodified) imagemagick source code
#
# -> If this is enabled, it will force enable
# a shared library build (because it is required)
#
# -> Requires a MagickWand build as well
#

JMAGICK_ENABLED := true


#------------------------------------------
# Enable or disable specific delegates here
#

LIBBZ2_ENABLED        := true
LIBFFTW_ENABLED       := true
LIBFREETYPE2_ENABLED  := true
LIBJPEG_TURBO_ENABLED := true
LIBLZMA_ENABLED       := true
LIBOPENJPEG_ENABLED   := true
LIBPNG_ENABLED        := true
LIBTIFF_ENABLED       := true
LIBWEBP_ENABLED       := true
LIBXML2_ENABLED       := true
LIBZLIB_ENABLED       := true
LIBLCMS2_ENABLED      := true

#------------------------------------------

# fix long windows paths causing build to fail (too many sources)
LOCAL_SHORT_COMMANDS := true
APP_SHORT_COMMANDS := true

#------------------------------------------
LOCAL_PATH := $(call my-dir)
include $(LOCAL_PATH)/make/postconfig.mk

```

[imagemagick-7-android-staticlib-arm64v8a.zip](https://github.com/cherryleafroad/Android-ImageMagick7/files/3999950/imagemagick-7-android-staticlib-arm64v8a.zip)

**Comment by aaandreyev** [comment]
wow, thank you, and especially for the prebuilt library. It's working like a charm now.

**Comment by cherryleafroad** [comment]
You're welcome. Please be advised that I just updated the version to the latest now. 7.0.8-63 -> 7.0.9-16

**Comment by kalyani-mango** [comment]
I am getting below error even though i have symbolic link created for same
![imp](https://user-images.githubusercontent.com/104356574/201613629-19e8358b-6bf4-4d30-a459-964ad17b2498.png)

**Comment by MolotovCherry** [comment]
@kalyani-mango Are you using jmagick?

**Comment by kalyani-mango** [comment]
No i am using ImageMagick 7.0

**Comment by MolotovCherry** [comment]
> No i am using ImageMagick 7.0

What is your setup? Imagemagick doesn't support Java out of the box (it's only a c library and binary), so it's impossible to get an unsatisfiedlinkerror unless you're trying to use Java bindings (with jmagick or similar libraries)
