### ISSUE TITLE
couldn't find "libjmagick-7.so" 

### ISSUE THREAD

**Issue by rupesh-kumar-lpu** [cherryleafroad/Android-ImageMagick7#5]
I am getting following exception when tried to use in my android studio project
couldn't find "libjmagick-7.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:984)
        at java.lang.System.loadLibrary(System.java:1562)
        at magick.Magick.<clinit>(Magick.java:22)
If I am missing anything ?
please help

**Comment by rupesh-kumar-lpu** [comment]
Actually I tried to run magick binary directly with chmod via process builder but it is giving me following error stream 
```
CANNOT LINK EXECUTABLE "data/data/com.example.app/files/magick":
library"libc++_shared.so" not found.
```
I placed the binary under data/data/com.example.app/files/ and ran it directly via process builder.
How can I do that correctly.
Do I need to "symlink" sorry I don't know what that means
Is the binary is dependent on .so file which it is saying is missing.
Waiting for your response.
Thanks!

**Comment by cherryleafroad** [comment]
jmagick is not built. So there's no jmagick library unless you build from source. The reason is that I even though jmagick likely works, it is unsupported by me due to its age. Regarding running the binary, please see my [example android app](https://github.com/cherryleafroad/Android-ImageMagick7/tree/master/libjmagick-7/android) for all asset layouts and supporting code.

**Comment by rupesh-kumar-lpu** [comment]
Hi thank you so much for your quick response.
I copied user folder to my getFilesDir() location and I will provide path to 
```
env.add("MAGICK_HOME=" + usrDir);
                env.add("ICU_DATA_DIR_PREFIX=" + usrDir);
```
I will also use this environment for my process of executing binary.
But can you please tell me what are "tmpDir" and "ref" here in the snippet,
Are they empty folders or I need to include some other assets.
Thanks again!
Best Regards
Rupesh Kumar

**Comment by rupesh-kumar-lpu** [comment]
okay sorry I just missed to read your lines properly that ref id ".so" path

**Comment by cherryleafroad** [comment]
Assets and their structure can be found in the [example android app](https://github.com/cherryleafroad/Android-ImageMagick7/tree/master/libjmagick-7/android/app/src/main/assets/usr). 

`TMPDIR` is required for imagemagick to do its work. When it's doing image work, it needs somewhere to write its temporary files to.

`ref` can be seen in the context of the code. `ref` is the Android context `Context ref = mContext.get();`, which is gotten from a WeakReference `mContext = new WeakReference<>(context);`, passed to the `AynsTask` (in order to not lock up the UI while processing). See [L83](https://github.com/cherryleafroad/Android-ImageMagick7/blob/master/libjmagick-7/android/app/src/main/java/com/example/project/MainActivity.java#L83) and [L207](https://github.com/cherryleafroad/Android-ImageMagick7/blob/master/libjmagick-7/android/app/src/main/java/com/example/project/MainActivity.java#L207) onwards.

**Comment by cherryleafroad** [comment]
"Is it necessary to use "AppInitializer.initialize" and related class files for MainActivity.java or just executing command will be sufficient?"
AppInitializer.initialize is only for jmagick. The rest in the class are for required for both. Copying asset files automatically, setting up symlinks, or setting the binary executable bit

**Comment by rupesh-kumar-lpu** [comment]
I saw saw your "build.gradle" file and added lines. I can clearly see libc++_shared.so under "data/app/package/lib/" directory. Is that the right path where the lib should be present?
I tried to execute the cmd using env as follows-
```
ArrayList<String> env = new ArrayList<>();
        env.add("TMPDIR=" + file.getAbsolutePath()+"/");
        env.add("MAGICK_HOME=" + getFilesDir().getAbsolutePath()+"/usr/");
        env.add("ICU_DATA_DIR_PREFIX=" +getFilesDir().getAbsolutePath()+"/usr/");
        env.add("LD_LIBRARY_PATH=" + this.getApplicationInfo().nativeLibraryDir);
        for (Map.Entry<String, String> entry : System.getenv().entrySet()) {
            env.add(entry.getKey() + "=" + entry.getValue());
        }
        String[] ENV = env.toArray(new String[0]);
        try {
            Process proc = Runtime.getRuntime().exec(ed, ENV);
        } catch (IOException e) {
            e.printStackTrace();
            Toast.makeText(this,"catch run",Toast.LENGTH_SHORT).show();
        }
```
I am getting the null pointer exception as
```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getAbsolutePath()' on a null object reference
        at com.iamtrk.imagemagicktest.MainActivity.executecommand(MainActivity.java:121)
        at com.iamtrk.imagemagicktest.MainActivity$1.onClick(MainActivity.java:66)
        at android.view.View.performClick(View.java:5647)
        at android.view.View$PerformClick.run(View.java:22462)
        at android.os.Handler.handleCallback(Handler.java:754)
```
But I can see the env defined folders are at proper location by device manager of android studio.
Thanks

**Comment by rupesh-kumar-lpu** [comment]
Here is the project link on google drive, I made it clear and small to understand <https://drive.google.com/open?id=15_zX4OHGqVicpBavuzsVtRBrAwP56vMj> Please do check my mainactivity.java whenever you having time. 
Thanks
